# -*- coding: utf-8 -*-
"""Desenfecção_Hospitalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TIgT-p82y6T6zuF1o8uTE_5yNB5PL5Rl

**Gerando dados Híbridos**
"""

import pandas as pd
import numpy as np

np.random.seed(42)

quantidade = 1500

dados = []

for i in range(quantidade):
    temperatura = np.random.uniform(20, 36)
    umidade = np.random.uniform(35, 90)
    voc = np.random.uniform(50, 900)
    co2 = np.random.uniform(400, 2500)
    particulas = np.random.uniform(5, 180)
    tempo_uso = np.random.uniform(0, 12)
    area_critica = np.random.choice([0, 1])

    pontos = 0

    if temperatura > 30:
        pontos += 1
    if umidade > 70:
        pontos += 1
    if voc > 500:
        pontos += 2
    if co2 > 1200:
        pontos += 1
    if particulas > 80:
        pontos += 2
    if tempo_uso > 6:
        pontos += 1
    if area_critica == 1:
        pontos += 1

    if pontos <= 2:
        risco = "baixo"
    elif pontos <= 5:
        risco = "medio"
    else:
        risco = "alto"

    dados.append([
        temperatura,
        umidade,
        voc,
        co2,
        particulas,
        tempo_uso,
        area_critica,
        risco
    ])

df = pd.DataFrame(dados, columns=[
    "temperatura",
    "umidade",
    "voc",
    "co2",
    "particulas",
    "tempo_uso",
    "area_critica",
    "risco"
])

df.to_csv("dataset_risco_contaminacao_hospitalar.csv", index=False)

df.head()

import pandas as pd

# Ler dataset
df = pd.read_excel("dataset_hibrido_risco_contaminacao.xlsx")

df.head()

"""Separar Entrdas e Saídas"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Variável alvo
y = df["risco"]

# Entradas
X = df.drop(columns=["risco", "origem"])

# Converter texto em números
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# Separar treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Treinar decision Tree"""

from sklearn.tree import DecisionTreeClassifier

modelo_tree = DecisionTreeClassifier()

modelo_tree.fit(X_train, y_train)

"""Treinar Random Forest"""

from sklearn.ensemble import RandomForestClassifier

modelo_rf = RandomForestClassifier()

modelo_rf.fit(X_train, y_train)

"""Fazer previsões"""

pred_tree = modelo_tree.predict(X_test)

pred_rf = modelo_rf.predict(X_test)

"""Avaliar os modelos"""

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print("===== Decision Tree =====")
print("Acurácia:", accuracy_score(y_test, pred_tree))
print(classification_report(y_test, pred_tree))

print("\n===== Random Forest =====")
print("Acurácia:", accuracy_score(y_test, pred_rf))
print(classification_report(y_test, pred_rf))

"""Gerar gráficos"""

import matplotlib.pyplot as plt

modelos = ['Decision Tree', 'Random Forest']
acuracias = [0.9604, 0.9618]

plt.figure(figsize=(6,4))
plt.bar(modelos, acuracias)

plt.ylabel('Acurácia')
plt.title('Comparação dos Algoritmos')

plt.ylim(0.90, 1.0)

plt.show()

import joblib

joblib.dump(modelo_rf, "modelo_random_forest.pkl")
joblib.dump(encoder, "encoder_risco.pkl")